### ISSUE TITLE
Could HiC-data be replaced by HiC-data generated by other comformation capture experiments like HiChIP or ChIA-PET?

### ISSUE THREAD

**Issue by Gemma-Zhang-326** [tanjimin/C.Origami#22]
Hi,

Dear author, the C.Origami is a beautiful job! 

Could I replace the HiC experiment data with HiChIP or ChIA-PET data during training my model? As we all know, they are techniques that incorporate chromatin immunoprecipitation(ChIP)-based enrichment and chromatin proximity ligation, thus reflecting three-dimensional conformation data that capture specific chromatin modification. I wonder if your model can compatible with similar data.

Best wishes
Gemma

**Comment by tanjimin** [comment]
Hi Gemma,

Great question! I haven't try C.Origami on data other than Hi-C, but I think it should work the same.

Jimin

**Comment by Gemma-Zhang-326** [comment]
Thanks for the quick replay. Glad to know that. I will try it and let you know if it works. Thanks again!

**Comment by Gemma-Zhang-326** [comment]
> Hi Gemma,
> 
> Great question! I haven't try C.Origami on data other than Hi-C, but I think it should work the same.
> 
> Jimin

Hi Jimin,

I recently tried training C.Origami with HiChIP data for my cell type, but the prediction images came out blank, which looked quite awkward. I'm unsure if this is due to data incompatibility. I plan to test it with Hi-C data from the same cell type for comparison.

Best regards,

Gemma

**Comment by Gemma-Zhang-326** [comment]
> > Hi Gemma,
> > Great question! I haven't try C.Origami on data other than Hi-C, but I think it should work the same.
> > Jimin
> 
> Hi Jimin,
> 
> I recently tried training C.Origami with HiChIP data for my cell type, but the prediction images came out blank, which looked quite awkward. I'm unsure if this is due to data incompatibility. I plan to test it with Hi-C data from the same cell type for comparison.
> 
> Best regards,
> 
> Gemma

I tried using HiChIP data, and C.Origami performed well on it. The previous issue was due to an error in preprocessing the HIC matrix. After reprocessing the HiC-Pro results with the `hicConvertFormat` tool to obtain the desired mcool file, everything worked correctly. The final val_loss converged to around 0.15. Just in case someone else encounters the same problem I did.

**Comment by tanjimin** [comment]
Glad it worked out!
