### ISSUE TITLE
Questions when I process the Hi-C data 

### ISSUE THREAD

**Issue by YCMaCY** [tanjimin/C.Origami#23]
Hi! Dear author.
I encountered problems when I tried to train the model of hg19. Neither using nf-core/hic(https://nf-co.re/hic) nor converting the .mcool file on 4DN into npz could I train the exact model, and the prediction result was empty. In addition, I found that the train loss were very low.
Could you please tell me more about how to process the Hi-C data？

**Comment by YCMaCY** [comment]
Thank you very much for your reply, I realized that the .hic file output from *nf-core/hic* pipeline is not compatible with corigami, I reused *HiC-Pro* to process Hi-C data and now I successfully trained the model for hg19.

**Comment by tanjimin** [comment]
Hi @YCMaCY , glad to know it worked on hg19! When I train the model I was used hic-bench (A tool from our group) and ICE normalization that comes with it. I think KR is better than no normalization. Normalization usually gives better quality and biologically more accurate given the bias in restriction enzymes.
