### ISSUE TITLE
Question about downscaling 10-kb matrix to 8192 bp resolution

### ISSUE THREAD

**Issue by zhang-jiankun** [tanjimin/C.Origami#25]
Hi @tanjimin ,

I really enjoyed using C.Origami, but I got a naive question that has been bothering me for a while. I was wondering how to downscale the 10-kb experimental Hi-C matrix to 8192 bp resolution in order to match the model outputs.

Best,

Jiankun

**Comment by tanjimin** [comment]
Hi Jiankun, this is the line where I performed transformation: 
https://github.com/tanjimin/C.Origami/blob/d5619eb8af7cb1c995c45396bb7c7e06aa5ec782/src/corigami/data/chromosome_dataset.py#L118

**Comment by zhang-jiankun** [comment]
Hi @tanjimin,

This is very clear. I would like to convert C.Origami prediction or even perturbed matrix to .cool file, and perform downstream analyses using the cooler package (https://cooler.readthedocs.io/en/latest/). Is it reasonable to resize the 256 x 256 output back to 210 x 210 and generate new cool file? I was also wondering if there is an implementation in the C.Origami repo.

Any advice would be greatly appreciated!

Best,


Jiankun

**Comment by tanjimin** [comment]
Yes, that is doable. This is also a feature I am currently working on: https://github.com/tanjimin/C.Origami/issues/24 although I don't have plan to include perturbed matrix. You can try to implement it and do a pull request!

**Comment by zhang-jiankun** [comment]
I got it. Thank you for your help!
