### ISSUE TITLE
Using CTCF chip-exo without input 

### ISSUE THREAD

**Issue by re2srm** [tanjimin/C.Origami#37]
Hello,

I have CTCF chip-exo data and unlike chip-seq it doesnt have an input sample. I have generated the bigwig file but cannot run  ctcf_norm.sh to normalize it as I dont have an input sample. Can I use the bigwig file directly without normalizing it?

I do have a chip-seq input sample from the same cell line but I am not sure if I should use that for normalizing the chip-exo data.
 
Thanks

**Comment by tanjimin** [comment]
The ChIP-seq has to be normalized with log2fc w.r.t. input. You can use the input sample from the same cell line as input data and see how it goes.

**Comment by re2srm** [comment]
Thanks. Will try that.

**Comment by re2srm** [comment]
I had another question about the atac-seq input files. I used the seqnslide atac pipeline to generate the atac bigwig file for my cell line. But I just noticed that the atac_pipeline.sh in the preprocessing folder subsamples 40M reads before running the pipeline. Is it a required step? Should I have subsampled 40M reads from my fastqs for generating the atac bigwig? Thanks

**Comment by re2srm** [comment]
Hi, another question about the ctcf input data. When I normalize my ctcf against input, there are regions where the log2fc w.r.t input is negative.  I also did this for some published ctcf data and got the same result. Were your normalized bigwig files similar? Or should I remove the negative values from the bigwig before using them as input. Thanks
