### ISSUE TITLE
Adding different ChIP-seq during the training phase ？

### ISSUE THREAD

**Issue by kir1to455** [tanjimin/C.Origami#41]
Hi，
Thank you for developing Corigami !
I have encountered some problems when I use corigami to train my data.

Could I Adding different  ChIP-seq (like H3K27ac, H3k4me3...) in training phase ?
![image](https://github.com/tanjimin/C.Origami/assets/87375686/ac0befd6-99e5-4e16-b501-573bc0cae37b)
Could simply add bigwig files of different ChIP-seq in "genomic_features"?

Best wishes,
Kirtio

**Comment by tanjimin** [comment]
Yes you definitely can

**Comment by tanjimin** [comment]
Definitely! You can add bigwigs and then adjust the number of genomic features here:
https://github.com/tanjimin/C.Origami/blob/e0c26c63623896cd666bcb6bd3ecf64196d73116/src/corigami/training/main.py#L232
