### ISSUE TITLE
Independant chance of returning sequence complement

### ISSUE THREAD

**Issue by kaboroevich** [tanjimin/C.Origami#43]
Hello,

I believe I've found an issue with the data augmentation method. The paper states, "we *reverse-complemented* the sequence and flipped the target Hi-C matrix with 0.5 probability."

However, in the corigami.data.ChromosomeDataset class, the [compliment](https://github.com/tanjimin/C.Origami/blob/e0c26c63623896cd666bcb6bd3ecf64196d73116/src/corigami/data/chromosome_dataset.py#L93) method generates its own random chance of whether the return value is complemented or returned as is. With the default `chance` parameter, it means that when a sequence is reversed, it's only complimented half the time. In other words. when using data augmentation, the returned sequence will be:

* 50% forward (original) sequence
* 25% reversed sequence
* 25% reverse-complimented sequence

To correct this, unless I overlooked something, the chance parameter and random number generation should be removed from the `complement` method (or set to > 1.0 when called).

**Comment by tanjimin** [comment]
Hi @kaboroevich That's a very good catch! Can you submit a pull request on this?

**Comment by kaboroevich** [comment]
I can do that. Should the request be made to the dev or main branch?

**Comment by tanjimin** [comment]
Please submit to dev and I'll merge them to main. Thanks!

**Comment by kaboroevich** [comment]
Sorry about that. The first pull-request was forked from main then submitted to dev and so had a lot of extra commits attached. I'm not sure if that would be an issue but I cleaned it up to a single commit.
