### ISSUE TITLE
Training and prediction at 5kb resolution

### ISSUE THREAD

**Issue by zhang-jiankun** [tanjimin/C.Origami#46]
Hi @tanjimin ,

I would like to perform training and prediction at 5kb resolution. I have made the following changes in the code:

> `self.res = 5000 # 5kb resolution`
> `self.bins = 104.8576 # 104.8576 bins 1048576 bp`
> `self.image_scale = 128 # IMPORTANT, scale 105 to 128`

I was wondering if this is enough. Are there any other things I should pay attention to?

**Comment by tanjimin** [comment]
Hi @zhang-jiankun these are reasonable edits. I think you also need to process your Hi-C data at 5kb resolution. There might be other small places that require modification. The quickest way to check would be printing the dimension of the input and inspecting target data as images from your edited dataloader.

**Comment by zhang-jiankun** [comment]
Thank you so much!

**Comment by zhang-jiankun** [comment]
Thank you so much!
